#!/usr/bin/env python3
"""Plan how the pictures cover the narration: a timing sheet for the edit.

  python production/timing_sheet.py --story lion_and_mouse_v5 [--lang en]

Reads the narration timing (work/stories/<story>/audio/<lang>/timing.json,
from voice/narrate_scenes.py), the spoken lines with their candidate shots
(stories/<story>/dialogue_coverage.json) and the shot list with start/end
images (stories/<story>/prompt_manifest.json). Writes

  stories/<story>/TIMING_SHEET.md   per scene: every line with start time and
                                    length, and the picture that covers it
  stories/<story>/timing_plan.json  the same, for tools (e.g. a rough cut)

How a shot is stretched over its narration (S = seconds it must cover; a
rendered clip is 81 frames = 5.06 s):
  S <= 5.6     the clip at normal speed (trimmed)
  S <= 10.6    the clip slowed down (speed 5.06/S; RIFE makes it smooth)
  S >  10.6    the clip at half speed (10.1 s), then its END image as a still
               with a slow push-in for the rest
Consecutive lines with the same candidate shots form a group; the group's time
is shared between those shots at line boundaries. When a group has no unused
shot left, it is covered by the last shot's end image (still, slow push-in).
This is a starting plan for the owner's edit in DaVinci, not a final cut.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from feltwillow import paths  # noqa: E402

CLIP = 81 / 16
PAUSE_SAME, PAUSE_CHANGE = 0.45, 0.70      # must match voice/narrate_scenes.py


def treatment(s: float) -> str:
    if s <= CLIP + 0.5:
        return "clip, normal speed"
    if s <= 2 * CLIP + 0.5:
        return f"clip slowed to {CLIP / s:.0%} speed"
    return f"clip at 50% ({2 * CLIP:.1f} s) + end image still, slow push-in {s - 2 * CLIP:.1f} s"


def fmt(t: float) -> str:
    return f"{int(t // 60)}:{t % 60:04.1f}"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--story", default="lion_and_mouse_v5")
    ap.add_argument("--lang", default="en")
    ap.add_argument("--audio-story", help="story whose work/ folder holds the narration "
                    "(default: --story)")
    args = ap.parse_args()
    sd = paths.STORIES / args.story
    timing = json.loads((paths.story_audio(args.audio_story or args.story, args.lang) / "timing.json").read_text())
    lines = json.loads((sd / "dialogue_coverage.json").read_text(encoding="utf-8"))["lines"]
    man = json.loads((sd / "prompt_manifest.json").read_text(encoding="utf-8"))
    img = {i["id"]: i.get("target") for i in man["images"]}
    shots = {s["id"]: s for s in man["shots"]}

    plan, md, film_t = [], [], 0.0
    md.append(f"# Timing sheet: {args.story} ({args.lang})\n")
    md.append("Generated by `production/timing_sheet.py` from the narration and the shot plan. "
              "Times are from the start of the film. A starting plan for the DaVinci edit: "
              "change freely. Clips are 5.06 s; see the script's docstring for the stretch rules.\n")
    summary = []
    for scene in sorted({ln["scene"] for ln in lines}):
        t = timing.get(str(scene))
        sl = [ln for ln in lines if ln["scene"] == scene]
        if not t:
            md.append(f"\n## Scene {scene:02d}: no narration yet\n")
            continue
        secs = {r["id"]: r["seconds"] for r in t["lines"]}
        # start time of each line inside the scene (same pauses as narrate_scenes.py)
        starts, cur, prev = {}, 0.0, None
        for ln in sl:
            if prev is not None:
                cur += PAUSE_SAME if prev == ln["speaker"] else PAUSE_CHANGE
            starts[ln["id"]] = cur
            cur += secs[ln["id"]]
            prev = ln["speaker"]
        # groups of consecutive lines with the same candidate shots
        groups = []
        for ln in sl:
            key = tuple(ln["candidate_coverage_shots"])
            if groups and groups[-1][0] == key:
                groups[-1][1].append(ln)
            else:
                groups.append((key, [ln]))
        used, segs, last_shot = set(), [], None
        for g, (cands, gl) in enumerate(groups):
            g_start = starts[gl[0]["id"]]
            nxt = starts[groups[g + 1][1][0]["id"]] if g + 1 < len(groups) else t["seconds"]
            free = [c for c in cands if c not in used]
            if not free:                                     # nothing new: hold a still
                still = cands[-1] if cands else last_shot
                segs.append(dict(shot=still, kind="still", start=g_start, seconds=nxt - g_start,
                                 lines=[ln["id"] for ln in gl],
                                 note="end image of the shot as a still, slow push-in (or reuse its clip)"))
                continue
            # split the group's lines between the free shots, balancing time
            k, total = len(free), nxt - g_start
            bounds, j = [], 1
            for i in range(len(gl) - 1):
                acc = starts[gl[i + 1]["id"]] - g_start
                if j < k and acc >= total * j / k:
                    bounds.append(i + 1)
                    j += 1
            parts = [gl[a:b] for a, b in zip([0] + bounds, bounds + [len(gl)])]
            free = free[:len(parts)]
            for p, (shot, pl) in enumerate(zip(free, parts)):
                s0 = starts[pl[0]["id"]]
                s1 = starts[parts[p + 1][0]["id"]] if p + 1 < len(parts) else nxt
                segs.append(dict(shot=shot, kind="clip", start=s0, seconds=s1 - s0,
                                 lines=[ln["id"] for ln in pl], note=treatment(s1 - s0)))
                used.add(shot)
                last_shot = shot
        clip_s = sum(min(s["seconds"], CLIP) for s in segs if s["kind"] == "clip")
        summary.append((scene, t["seconds"], len({s["shot"] for s in segs if s["kind"] == "clip"}), clip_s))
        md.append(f"\n## Scene {scene:02d} ({fmt(film_t)} - {fmt(film_t + t['seconds'])}, "
                  f"{t['seconds']:.1f} s, audio `scene{scene:02d}.wav`)\n")
        md.append("| Start | Length | Picture | How | Lines |\n|---|---|---|---|---|")
        for s in segs:
            sh = shots.get(s["shot"], {})
            pics = (f"`{s['shot']}`" + (f" (end image: `{Path(img.get(sh.get('end_image')) or '').name}`)"
                                        if s["kind"] == "still" else ""))
            md.append(f"| {fmt(film_t + s['start'])} | {s['seconds']:.1f} s | {pics} | {s['note']} | "
                      f"{', '.join(s['lines'])} |")
            plan.append(dict(scene=scene, film_start=round(film_t + s["start"], 2), **{k: v for k, v in s.items()},
                             start_image=img.get(sh.get("start_image")), end_image=img.get(sh.get("end_image"))))
        md.append("\n<details><summary>Lines</summary>\n")
        for ln in sl:
            md.append(f"- `{ln['id']}` {fmt(film_t + starts[ln['id']])} ({secs[ln['id']]:.1f} s) "
                      f"**{ln['speaker']}**: {ln['text']}")
        md.append("\n</details>")
        film_t += t["seconds"]
    md.insert(2, "\n## Summary\n\n| Scene | Narration | Shots used | Clip time at normal speed | Covered by slow-down or stills |\n|---|---|---|---|---|\n"
              + "\n".join(f"| {s} | {a:.1f} s | {n} | {c:.1f} s | {a - c:.1f} s |" for s, a, n, c in summary)
              + f"\n| **total** | **{fmt(sum(a for _, a, _, _ in summary))}** | {sum(n for _, _, n, _ in summary)} | "
              f"{sum(c for *_, c in summary) / 60:.1f} min | {sum(a - c for _, a, _, c in summary) / 60:.1f} min |\n")
    (sd / "TIMING_SHEET.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    (sd / "timing_plan.json").write_text(json.dumps(dict(story=args.story, lang=args.lang, clip_seconds=CLIP,
                                                         segments=plan), indent=2))
    print(f"film {fmt(film_t)}; {len(plan)} segments -> {sd / 'TIMING_SHEET.md'}")


if __name__ == "__main__":
    main()
